// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyPro2.API.Data;

#nullable disable

namespace MoneyPro2.API.Migrations
{
    [DbContext(typeof(MoneyPro2DataContext))]
    [Migration("20230829215910_AccountGroup_Class")]
    partial class AccountGroup_Class
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("Seq_GrupoContaID");

            modelBuilder.HasSequence<int>("Seq_MoedaID");

            modelBuilder.Entity("MoneyPro2.Domain.Entities.AccountGroup", b =>
                {
                    b.Property<int>("GrupoContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [Seq_GrupoContaID]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("GrupoContaId"), "Seq_GrupoContaID");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Apelido");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("Ativo")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Descricao");

                    b.Property<bool?>("FluxoCredito")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("FluxoCredito")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("FluxoDisponivel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("FluxoDisponivel")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("Ordem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Ordem")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("Painel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("Painel")
                        .HasDefaultValueSql("0");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuarioId");

                    b.HasKey("GrupoContaId");

                    b.HasIndex(new[] { "UsuarioId", "Apelido" }, "IX_AccountGroup_UsuarioID_Apelido")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "UsuarioId", "Apelido" }, "IX_AccountGroup_UsuarioID_Apelido"), false);

                    b.HasIndex(new[] { "UsuarioId", "Ordem" }, "IX_AccountGroup_UsuarioID_Ordem");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "UsuarioId", "Ordem" }, "IX_AccountGroup_UsuarioID_Ordem"), false);

                    b.ToTable("GrupoConta", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.Coin", b =>
                {
                    b.Property<int>("MoedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [Seq_MoedaID]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("MoedaId"), "Seq_MoedaID");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Apelido");

                    b.Property<int?>("BancoCentral")
                        .HasColumnType("INT")
                        .HasColumnName("BancoCentral");

                    b.Property<string>("Eletronica")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Eletronica");

                    b.Property<bool?>("MoedaVirtual")
                        .IsRequired()
                        .HasColumnType("BIT")
                        .HasColumnName("MoedaVirtual");

                    b.Property<string>("Observacao")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Observacao");

                    b.Property<bool>("Padrao")
                        .HasColumnType("BIT")
                        .HasColumnName("Padrao");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Simbolo");

                    b.HasKey("MoedaId");

                    b.HasIndex(new[] { "Apelido" }, "IX_Coin_Apelido")
                        .IsUnique();

                    b.HasIndex(new[] { "Simbolo" }, "IX_Coin_Simbolo")
                        .IsUnique();

                    b.ToTable("Moeda", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstituicaoId"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Apelido");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("Ativo")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Descricao");

                    b.Property<int?>("TipoInstituicaoId")
                        .IsRequired()
                        .HasColumnType("INT")
                        .HasColumnName("TipoInstituicaoId");

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("UserId");

                    b.HasKey("InstituicaoId");

                    b.HasIndex("TipoInstituicaoId");

                    b.HasIndex(new[] { "UserId", "TipoInstituicaoId", "Apelido" }, "IX_Instituicao_UserId_TipoInstituicaoId_Apelido")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "UserId", "TipoInstituicaoId", "Apelido" }, "IX_Instituicao_UserId_TipoInstituicaoId_Apelido"), false);

                    b.ToTable("Instituicao", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.InstitutionType", b =>
                {
                    b.Property<int>("TipoInstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoInstituicaoId"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Apelido");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasColumnName("Ativo")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Descricao");

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("UserId");

                    b.HasKey("TipoInstituicaoId");

                    b.HasIndex(new[] { "UserId", "Apelido" }, "IX_TipoInstituicao_UserId_Apelido")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "UserId", "Apelido" }, "IX_TipoInstituicao_UserId_Apelido"), false);

                    b.ToTable("TipoInstituicao", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Criptografada")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("CHAR")
                        .HasColumnName("PasswordHash");

                    b.Property<bool?>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("UserName");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Username" }, "IX_User_Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("LoginTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "LoginTime" }, "IX_UserLogin_UserId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "UserId", "LoginTime" }, "IX_UserLogin_UserId"), false);

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.AccountGroup", b =>
                {
                    b.HasOne("MoneyPro2.Domain.Entities.User", "User")
                        .WithMany("AccountGroups")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AccountGroup_User_UsuarioID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.Institution", b =>
                {
                    b.HasOne("MoneyPro2.Domain.Entities.InstitutionType", "InstitutionType")
                        .WithMany("Institutions")
                        .HasForeignKey("TipoInstituicaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Instituicao_TipoInstituicao_TipoInstituicaoId");

                    b.HasOne("MoneyPro2.Domain.Entities.User", "User")
                        .WithMany("Institutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Instituicao_User_UserId");

                    b.Navigation("InstitutionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.InstitutionType", b =>
                {
                    b.HasOne("MoneyPro2.Domain.Entities.User", "User")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TipoInstituicao_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.User", b =>
                {
                    b.OwnsOne("MoneyPro2.Domain.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Conteudo")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("CHAR")
                                .HasColumnName("CPF");

                            b1.HasKey("UserId");

                            b1.HasIndex("Conteudo")
                                .IsUnique()
                                .HasDatabaseName("IX_User_CPF")
                                .HasFilter("[CPF] IS NOT NULL");

                            SqlServerIndexBuilderExtensions.IsClustered(b1.HasIndex("Conteudo"), false);

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MoneyPro2.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("IX_User_Email")
                                .HasFilter("[Email] IS NOT NULL");

                            SqlServerIndexBuilderExtensions.IsClustered(b1.HasIndex("Address"), false);

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("CPF");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("MoneyPro2.Domain.Entities.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserLogin_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.InstitutionType", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("MoneyPro2.Domain.Entities.User", b =>
                {
                    b.Navigation("AccountGroups");

                    b.Navigation("InstitutionTypes");

                    b.Navigation("Institutions");

                    b.Navigation("UserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
